version: '3.8'

services:
  food-receipt-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-receipt-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./.env:/app/.env:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - receipt-analyzer-network

  food-receipt-analyzer-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-receipt-analyzer-dev
    ports:
      - "8502:8501"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.git
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - receipt-analyzer-network

networks:
  receipt-analyzer-network:
    driver: bridge

volumes:
  receipt_data:
    driver: local
  receipt_uploads:
    driver: local